version: '3.7'
services:
    app:
        build:
            context: .
            dockerfile: dockerfile/Dockerfile
        image: 'laravelapp'
        ports:
            - 8080:80
        volumes:
            - ./:/var/www/html
