# Deployment là 1 phương pháp của kubernate giúp cập nhật version mới của ứng dụng dễ dàng
# thông qua 2 kiểu strategy để deploy là Recreate và RollingUpdate,
# các version có history có thể rollback hoặc rollout giữa các version mà ko cần chạy lại CI/CD
# Luồng: Deployment tạo và quản lý ReplicaSet -> ReplicaSet tạo và quản lý Pod -> Pod run container.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernate-circle-ci # tên của deployment để tương tác với deployment
spec:
  replicas: 3 # số lượng replica Pods, mặc định là 1
  strategy:
    rollingUpdate:
      maxSurge: 1 # set số lượng Pod tối đa có thể tạo vượt số lượng Pod mong muốn
      maxUnavailable: 0 # set số lượng Pod tối đa không có trong quá trình update
    type: RollingUpdate
# Recreate - xóa toàn bộ version cũ, rồi deploy 1 version mới lên ứng dụng
#          - sẽ mất 1 khoảng thời gian downtime với client vì xóa toàn bộ version cũ và deploy version mới cho ứng dụng
# RollingUpdate - chạy song song 2 version mới và cũ, deploy version mới lên từng ứng dụng và xóa version cũ
#               - giảm thời gian downtime với client
#               - version mới và cũ chạy chung 1 lúc gây khó khăn viết script test quá trình deploy
  revisionHistoryLimit: 1 # số lượng revision history của ReplicaSet muốn lưu
  selector:
    matchLabels:
      name: kubernate-circle-ci
  template:
    metadata:
      labels:
        name: kubernate-circle-ci
    spec:
      containers:
        - name: kubernate-circle-ci
#          resources:
#            requests:
#              cpu: 200m
#              memory: 512Mi
#            limits:
#              memory: 512Mi
          image: gcr.io/kubernate-circle-ci/busybox:${CIRCLE_SHA1}-${CIRCLE_BUILD_NUM}
          # không nên để :latest vì khó theo dõi version image và rollback đúng version
          imagePullPolicy: Always # nếu đã tồn tại cache image, sẽ sử dụng cache còn ko sẽ pull và sử dụng
          command: ["apache2-foreground"] # this command: apache2 -D FOREGROUND => giữ cho server apache chạy liên tục
          ###
          ports:
            - containerPort: 80
