apiVersion: v1
kind: Service
metadata:
  name: svc-kubernate-circle-ci
  labels:
    name: svc-kubernate-circle-ci
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30502
  selector:
    name: kubernate-circle-ci
