apiVersion: v1
kind: Service
# service để chạy ứng dụng
metadata:
  name: svc-kubernate-circle-ci
  labels:
    name: svc-kubernate-circle-ci
spec:
  type: LoadBalancer
# ClusterIP - chỉ có thể truy cập dịch vụ này trong Cluster thông qua 1 IP nội bộ (Cluster IP)
# NodePort - có thể truy cập thông qua 1 IP nội bộ trong Cluster (giống như ClusterIP),
#          - hoặc có thể truy cập từ IP bên ngoài đã được định nghĩa (Node IP)
#          - Kubernetes phân bố port theo 1 khoảng nhất định từ 30000-32767
# LoadBalancer - như 1 dạng public IP (LoadBalancer IP), tất cả đều có thể truy cập
# https://stackoverflow.com/questions/41509439/whats-the-difference-between-clusterip-nodeport-and-loadbalancer-service-types
  ports:
    - port: 80
      #nodePort: 30502
  selector:
    name: kubernate-circle-ci
